name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: yarn install

      - name: Create Private Key File
        run: |
          mkdir -p src/keys
          cat > src/keys/private-key.js << 'EOL'
          export const privateKey = `-----BEGIN PRIVATE KEY-----
          ${{ secrets.PRIVATE_KEY }}
          -----END PRIVATE KEY-----`;
          EOL

      - name: Build
        env:
          CI: false
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
          REACT_APP_ENCRYPTED_CREDENTIALS_PATH: ${{ secrets.REACT_APP_ENCRYPTED_CREDENTIALS_PATH }}
        run: |
          echo "REACT_APP_SUPABASE_URL=$REACT_APP_SUPABASE_URL" >> .env.production
          echo "REACT_APP_SUPABASE_ANON_KEY=$REACT_APP_SUPABASE_ANON_KEY" >> .env.production
          echo "REACT_APP_ENCRYPTED_CREDENTIALS_PATH=$REACT_APP_ENCRYPTED_CREDENTIALS_PATH" >> .env.production
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: Duy-Thanh/blog
          publish_branch: gh-pages
          publish_dir: ./build
          force_orphan: true 